
CREATE TABLE `triangle` (
  `A` int(10) UNSIGNED DEFAULT NULL;
  `B` int(10) UNSIGNED NOT NULL;
  `C` int(10) UNSIGNED NOT NULL;
  `ID` int(11) NOT NULL AUTO_INCREMENT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



