CREATE DATABASE IF NOT EXISTS triangles;
USE triangles;

CREATE TABLE IF NOT EXISTS `triangle` (
  `A` int(10) UNSIGNED DEFAULT NULL,
  `B` int(10) UNSIGNED NOT NULL,
  `C` int(10) UNSIGNED NOT NULL,
  `ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

